name 'workstation'
maintainer 'Amartin'
maintainer_email 'you@example.com'
license 'all_public'
description 'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version '0.1.0'
